[package]
name = "hydra-macros"
version = "0.1.27"
edition = "2021"
license.workspace = true
repository.workspace = true
categories.workspace = true
description = "Macros for the hydra framework."

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2.0", features = ["full"] }
