[package]
name = "hydra-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hydra = { path = "../hydra", default-features = false, features = ["tracing"] }
tracing = "0.1"

serde.workspace = true
